export const publisherArea = [
  {id:'1', area:'DI Aceh'},
  {id:'2', area:'DKI Jakarta'},
  {id:'3', area:'Banten'},
  {id:'4', area:'Jawa Barat'},
  {id:'5', area:'Jawa Tengah'},
  {id:'6', area:'Jawa Timur'},
  {id:'7', area:'DI Yogyakarta'},
  {id:'8', area:'Lampung'},
  {id:'9', area:'Sumatra Selatan'},
  {id:'10', area:'Riau'},
  {id:'11', area:'Sumatra Barat'},
  {id:'12', area:'Sumatra Utara'},
  {id:'13', area:'Kep. Riau'},
  {id:'14', area:'Kalimantan Selatan'},
  {id:'15', area:'Kalimantan Barat'},
  {id:'16', area:'Kalimantan Timur'},
  {id:'17', area:'Kalimantan Tengah'},
  {id:'18', area:'Sulawesi Selatan'},
  {id:'19', area:'Sulawesi'},
  {id:'20', area:'Bali'},
  {id:'21', area:'Nusa Tenggara Timur'},
  {id:'22', area:'Nusa Tenggara Barat'}
]