export const publisherArea = [
  {'1':'DI Aceh'},
  {'2':'DKI Jakarta'},
  {'3':'Banten'},
  {'4':'Jawa Barat'},
  {'5':'Jawa Tengah'},
  {'6':'Jawa Timur'},
  {'7':'DI Yogyakarta'},
  {'8':'Lampung'},
  {'9':'Sumatra Selatan'},
  {'10':'Riau'},
  {'11':'Sumatra Barat'},
  {'12':'Sumatra Utara'},
  {'13':'Kep. Riau'},
  {'14':'Kalimantan Selatan'},
  {'15':'Kalimantan Barat'},
  {'16':'Kalimantan Timur'},
  {'17':'Kalimantan Tengah'},
  {'18':'Sulawesi Selatan'},
  {'19':'Sulawesi'},
  {'20':'Bali'},
  {'21':'Nusa Tenggara Timur'},
  {'22':'Nusa Tenggara Barat'}
]